# Generated by Django 4.2.1 on 2023-05-30 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=30, verbose_name='Nombre de categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de comuna')),
                ('nombreComuna', models.CharField(max_length=70, verbose_name='Nombre de comuan')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreRegion', models.CharField(max_length=30, verbose_name='Nombre de region')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de usuario')),
                ('nombreUsuario', models.CharField(max_length=70, verbose_name='Nombre del usuario')),
                ('apellidoUsuario', models.CharField(max_length=70, verbose_name='Apellido del usuario')),
                ('rutUsuario', models.IntegerField(verbose_name='Rut del usuario')),
                ('emailUsuario', models.EmailField(max_length=30, unique=True, verbose_name='Email del usuario')),
                ('contraseniaUsuario', models.CharField(max_length=30, verbose_name='Contraseña del usuario')),
                ('direccionUsuario', models.CharField(max_length=70, null=True, verbose_name='Dirección del usuario')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('caracteristicaProducto', models.CharField(max_length=255, verbose_name='Descripcion del producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio de producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ListaCompras',
            fields=[
                ('idListaCompras', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la lista de compras')),
                ('valorTotalCompra', models.IntegerField(blank=True, null=True, verbose_name='Valor total de compra')),
                ('cantidadProductos', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de productos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
