# Generated by Django 4.2.1 on 2023-07-01 04:47

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categoria_idcategoria_alter_comuna_idcomuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='nombreCategoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='nombreProducto'),
        ),
    ]
