# Generated by Django 4.2.1 on 2023-07-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_activo_categoria_slug_producto_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rutUsuario',
            field=models.CharField(max_length=70, verbose_name='Rut del usuario'),
        ),
    ]
