# Generated by Django 4.2.1 on 2023-07-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usuario_comuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id Contacto')),
                ('nombreCompleto', models.CharField(max_length=70, verbose_name='Nombre de enviante')),
                ('emailUsuario', models.EmailField(max_length=30, verbose_name='Email de enviante')),
                ('asunto', models.CharField(max_length=30, verbose_name='asunto del mensaje')),
                ('mensaje', models.TextField(max_length=1000)),
            ],
        ),
    ]
