# Generated by Django 4.2.1 on 2023-07-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id Contacto')),
                ('nombreDuenio', models.CharField(max_length=70, verbose_name='Nombre de enviante')),
                ('emailDuenio', models.EmailField(max_length=30, verbose_name='Email de enviante')),
                ('fechaCompra', models.CharField(max_length=10, verbose_name='fecha de compra')),
                ('codBoleta', models.CharField(max_length=10, verbose_name='Codigo boleta')),
                ('numChasis', models.CharField(max_length=10, verbose_name='Número de chasis')),
                ('rutDuenio', models.CharField(max_length=15, verbose_name='Rut de Dueño')),
                ('descripcion', models.TextField(max_length=1000)),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
            ],
        ),
    ]
